#!/usr/bin/env ts-node
/**
 * =============================================================================
 * Generate Environment Files from CDK Outputs
 * =============================================================================
 * 
 * This script fetches CloudFormation stack outputs and generates .env files
 * for frontend and backend applications.
 * 
 * Usage:
 *   npx ts-node scripts/generate-env.ts dev
 *   npx ts-node scripts/generate-env.ts prod
 * 
 * =============================================================================
 */

import { CloudFormationClient, DescribeStacksCommand } from '@aws-sdk/client-cloudformation';
import * as fs from 'fs';
import * as path from 'path';

type Environment = 'dev' | 'prod';

interface StackOutputs {
  [key: string]: string;
}

async function getStackOutputs(stackName: string, region: string): Promise<StackOutputs> {
  const client = new CloudFormationClient({ region });
  
  try {
    const command = new DescribeStacksCommand({ StackName: stackName });
    const response = await client.send(command);
    
    const outputs: StackOutputs = {};
    const stack = response.Stacks?.[0];
    
    if (stack?.Outputs) {
      for (const output of stack.Outputs) {
        if (output.OutputKey && output.OutputValue) {
          outputs[output.OutputKey] = output.OutputValue;
        }
      }
    }
    
    return outputs;
  } catch (error: any) {
    console.warn(`Warning: Could not fetch outputs from ${stackName}: ${error.message}`);
    return {};
  }
}

async function generateEnvFiles(env: Environment): Promise<void> {
  const region = 'us-east-2';
  const stackPrefix = `barkbase-${env}`;
  
  console.log(`\n🔍 Fetching stack outputs for ${env} environment...\n`);
  
  // Fetch outputs from all stacks
  const [networkOutputs, databaseOutputs, authOutputs, servicesOutputs, apiOutputs] = await Promise.all([
    getStackOutputs(`${stackPrefix}-network`, region),
    getStackOutputs(`${stackPrefix}-database`, region),
    getStackOutputs(`${stackPrefix}-auth`, region),
    getStackOutputs(`${stackPrefix}-services`, region),
    getStackOutputs(`${stackPrefix}-api`, region),
  ]);
  
  // Merge all outputs
  const allOutputs = {
    ...networkOutputs,
    ...databaseOutputs,
    ...authOutputs,
    ...servicesOutputs,
    ...apiOutputs,
  };
  
  console.log('📋 Found outputs:', Object.keys(allOutputs).join(', ') || 'none');
  
  // Generate frontend .env
  const frontendEnv = generateFrontendEnv(env, allOutputs, region);
  const frontendEnvPath = path.join(__dirname, '../../../frontend', env === 'prod' ? '.env.production' : '.env.development');
  
  fs.writeFileSync(frontendEnvPath, frontendEnv);
  console.log(`\n✅ Generated: ${frontendEnvPath}`);
  
  // Generate backend .env
  const backendEnv = generateBackendEnv(env, allOutputs, region);
  const backendEnvPath = path.join(__dirname, '../../../backend', env === 'prod' ? '.env.production' : '.env.development');
  
  fs.writeFileSync(backendEnvPath, backendEnv);
  console.log(`✅ Generated: ${backendEnvPath}`);
  
  // Also write a combined outputs file for reference
  const outputsPath = path.join(__dirname, `../outputs-${env}.json`);
  fs.writeFileSync(outputsPath, JSON.stringify(allOutputs, null, 2));
  console.log(`✅ Generated: ${outputsPath}`);
  
  console.log('\n🎉 Environment files generated successfully!\n');
}

function generateFrontendEnv(env: Environment, outputs: StackOutputs, region: string): string {
  const userPoolId = outputs.UserPoolId || '<PENDING_DEPLOY>';
  const clientId = outputs.UserPoolClientId || '<PENDING_DEPLOY>';
  const cognitoDomain = outputs.CognitoDomain || '<PENDING_DEPLOY>';
  const apiUrl = outputs.ApiUrl || '<PENDING_DEPLOY>';
  
  const redirectUri = env === 'prod' 
    ? 'https://app.barkbase.io/auth/callback'
    : 'http://localhost:5173/auth/callback';
  
  const logoutUri = env === 'prod'
    ? 'https://app.barkbase.io'
    : 'http://localhost:5173';
  
  return `# =============================================================================
# BarkBase Frontend Environment - ${env.toUpperCase()}
# =============================================================================
# Generated by CDK on ${new Date().toISOString()}
# Do not edit manually - regenerate using: npm run generate-env:${env}
# =============================================================================

# Authentication Mode: 'embedded' (direct Cognito) or 'hosted' (Cognito Hosted UI)
VITE_AUTH_MODE=embedded

# AWS Region
VITE_AWS_REGION=${region}

# Cognito Configuration
VITE_USER_POOL_ID=${userPoolId}
VITE_CLIENT_ID=${clientId}
VITE_COGNITO_DOMAIN=${cognitoDomain}

# API Gateway
VITE_API_URL=${apiUrl}
VITE_API_BASE_URL=${apiUrl}

# OAuth URLs
VITE_REDIRECT_URI=${redirectUri}
VITE_LOGOUT_URI=${logoutUri}
`;
}

function generateBackendEnv(env: Environment, outputs: StackOutputs, region: string): string {
  const dbSecretArn = outputs.DbSecretArn || '<PENDING_DEPLOY>';
  const dbEndpoint = outputs.DbEndpoint || '<PENDING_DEPLOY>';
  const userPoolId = outputs.UserPoolId || '<PENDING_DEPLOY>';
  const clientId = outputs.UserPoolClientId || '<PENDING_DEPLOY>';
  const jwksUrl = outputs.JwksUrl || `https://cognito-idp.${region}.amazonaws.com/${userPoolId}/.well-known/jwks.json`;
  
  return `# =============================================================================
# BarkBase Backend Environment - ${env.toUpperCase()}
# =============================================================================
# Generated by CDK on ${new Date().toISOString()}
# Do not edit manually - regenerate using: npm run generate-env:${env}
# =============================================================================

# Environment
NODE_ENV=${env === 'prod' ? 'production' : 'development'}

# AWS Region
AWS_REGION=${region}
AWS_REGION_DEPLOY=${region}

# Database Configuration
DB_SECRET_ARN=${dbSecretArn}
DB_HOST=${dbEndpoint}
DB_PORT=5432
DB_NAME=barkbase

# Cognito Configuration
COGNITO_USER_POOL_ID=${userPoolId}
COGNITO_CLIENT_ID=${clientId}
COGNITO_JWKS_URL=${jwksUrl}
COGNITO_ISSUER_URL=https://cognito-idp.${region}.amazonaws.com/${userPoolId}

# CORS Origins
CORS_ORIGINS=${env === 'prod' ? 'https://barkbase.io,https://app.barkbase.io' : 'http://localhost:5173,http://localhost:3000'}
`;
}

// Main execution
const env = (process.argv[2] || 'dev') as Environment;

if (!['dev', 'prod'].includes(env)) {
  console.error('Usage: npx ts-node scripts/generate-env.ts [dev|prod]');
  process.exit(1);
}

generateEnvFiles(env).catch((error) => {
  console.error('Failed to generate env files:', error);
  process.exit(1);
});

