/**
 * Demo Data Seeder
 *
 * Seeds comprehensive demo data into sessionStorage on first load.
 * Data persists until browser is closed or user clicks "Reset Demo"
 */

export const DEMO_STORAGE_KEY = 'barkbase-demo-data';

// ============================================================================
// DEMO DATA
// ============================================================================

const owners = [
  {
    id: 1,
    recordId: 1,
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@email.com',
    phone: '(555) 123-4567',
    address: '123 Oak Street',
    city: 'Portland',
    state: 'OR',
    zipCode: '97201',
    status: 'ACTIVE',
    notes: 'Preferred customer, always books in advance',
    totalSpent: 2450.00,
    visitCount: 12,
    lifetimeValue: 2450.00,
    pendingBalance: 0,
    lastVisit: '2024-12-20',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    recordId: 2,
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'mchen@email.com',
    phone: '(555) 234-5678',
    address: '456 Maple Avenue',
    city: 'Portland',
    state: 'OR',
    zipCode: '97202',
    status: 'ACTIVE',
    notes: '',
    totalSpent: 1875.50,
    visitCount: 8,
    lifetimeValue: 1875.50,
    pendingBalance: 125.00,
    lastVisit: '2024-12-18',
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 3,
    recordId: 3,
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 345-6789',
    address: '789 Pine Lane',
    city: 'Lake Oswego',
    state: 'OR',
    zipCode: '97034',
    status: 'ACTIVE',
    notes: 'VIP customer, multiple pets',
    totalSpent: 4200.00,
    visitCount: 24,
    lifetimeValue: 4200.00,
    pendingBalance: 0,
    lastVisit: '2024-12-22',
    createdAt: '2023-11-10T09:00:00Z',
  },
  {
    id: 4,
    recordId: 4,
    firstName: 'David',
    lastName: 'Thompson',
    email: 'dthompson@email.com',
    phone: '(555) 456-7890',
    address: '321 Cedar Road',
    city: 'Beaverton',
    state: 'OR',
    zipCode: '97005',
    status: 'INACTIVE',
    notes: 'Moved out of area',
    totalSpent: 650.00,
    visitCount: 3,
    lifetimeValue: 650.00,
    pendingBalance: 0,
    lastVisit: '2024-06-15',
    createdAt: '2024-03-01T11:00:00Z',
  },
  {
    id: 5,
    recordId: 5,
    firstName: 'Jessica',
    lastName: 'Williams',
    email: 'jwilliams@email.com',
    phone: '(555) 567-8901',
    address: '654 Birch Street',
    city: 'Portland',
    state: 'OR',
    zipCode: '97214',
    status: 'ACTIVE',
    notes: '',
    totalSpent: 980.00,
    visitCount: 5,
    lifetimeValue: 980.00,
    pendingBalance: 45.00,
    lastVisit: '2024-12-19',
    createdAt: '2024-04-12T16:00:00Z',
  },
];

const pets = [
  {
    id: 1,
    recordId: 1,
    name: 'Buddy',
    species: 'Dog',
    breed: 'Golden Retriever',
    ownerId: 1,
    birthdate: '2020-03-15',
    weight: 75,
    color: 'Golden',
    gender: 'Male',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP123456',
    notes: 'Friendly, loves to play fetch',
    behaviorFlags: [],
    feedingInstructions: '2 cups twice daily',
    medicationInstructions: '',
    avatarUrl: null,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    recordId: 2,
    name: 'Luna',
    species: 'Dog',
    breed: 'German Shepherd',
    ownerId: 2,
    birthdate: '2019-07-22',
    weight: 65,
    color: 'Black and Tan',
    gender: 'Female',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP234567',
    notes: 'Very protective, warm up slowly to new people',
    behaviorFlags: ['CAUTION_WITH_STRANGERS'],
    feedingInstructions: '2.5 cups twice daily',
    medicationInstructions: 'Joint supplement daily',
    avatarUrl: null,
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 3,
    recordId: 3,
    name: 'Max',
    species: 'Dog',
    breed: 'French Bulldog',
    ownerId: 3,
    birthdate: '2021-11-08',
    weight: 28,
    color: 'Fawn',
    gender: 'Male',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP345678',
    notes: 'Snores loudly, loves belly rubs',
    behaviorFlags: [],
    feedingInstructions: '1 cup twice daily',
    medicationInstructions: '',
    avatarUrl: null,
    createdAt: '2023-11-10T09:00:00Z',
  },
  {
    id: 4,
    recordId: 4,
    name: 'Bella',
    species: 'Cat',
    breed: 'Maine Coon',
    ownerId: 3,
    birthdate: '2020-05-12',
    weight: 15,
    color: 'Tabby',
    gender: 'Female',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP456789',
    notes: 'Independent but affectionate',
    behaviorFlags: [],
    feedingInstructions: '1/2 cup twice daily',
    medicationInstructions: '',
    avatarUrl: null,
    createdAt: '2023-11-10T09:00:00Z',
  },
  {
    id: 5,
    recordId: 5,
    name: 'Cooper',
    species: 'Dog',
    breed: 'Labrador Retriever',
    ownerId: 4,
    birthdate: '2018-09-30',
    weight: 80,
    color: 'Chocolate',
    gender: 'Male',
    status: 'inactive',
    isNeutered: true,
    microchipId: 'CHIP567890',
    notes: 'Senior dog, needs extra care',
    behaviorFlags: ['SENIOR_CARE'],
    feedingInstructions: 'Senior formula, 2 cups twice daily',
    medicationInstructions: 'Arthritis medication morning',
    avatarUrl: null,
    createdAt: '2024-03-01T11:00:00Z',
  },
  {
    id: 6,
    recordId: 6,
    name: 'Daisy',
    species: 'Dog',
    breed: 'Beagle',
    ownerId: 5,
    birthdate: '2022-02-14',
    weight: 25,
    color: 'Tricolor',
    gender: 'Female',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP678901',
    notes: 'Very vocal, loves treats',
    behaviorFlags: ['ESCAPE_ARTIST'],
    feedingInstructions: '1.5 cups twice daily',
    medicationInstructions: '',
    avatarUrl: null,
    createdAt: '2024-04-12T16:00:00Z',
  },
  {
    id: 7,
    recordId: 7,
    name: 'Rocky',
    species: 'Dog',
    breed: 'Boxer',
    ownerId: 1,
    birthdate: '2021-06-20',
    weight: 70,
    color: 'Brindle',
    gender: 'Male',
    status: 'active',
    isNeutered: true,
    microchipId: 'CHIP789012',
    notes: 'High energy, needs lots of exercise',
    behaviorFlags: ['HIGH_ENERGY'],
    feedingInstructions: '2.5 cups twice daily',
    medicationInstructions: '',
    avatarUrl: null,
    createdAt: '2024-01-15T10:00:00Z',
  },
];

const vaccinations = [
  {
    id: 1,
    recordId: 1,
    petId: 1,
    vaccineName: 'Rabies',
    type: 'Rabies',
    administeredAt: '2024-01-15',
    administeredDate: '2024-01-15',
    expiresAt: '2025-01-15',
    expirationDate: '2025-01-15',
    provider: 'Dr. Smith, Portland Vet Clinic',
    veterinarian: 'Dr. Smith',
    lotNumber: 'RAB2024-001',
    status: 'current',
    notes: '',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    recordId: 2,
    petId: 1,
    vaccineName: 'DHPP',
    type: 'DHPP',
    administeredAt: '2024-01-15',
    administeredDate: '2024-01-15',
    expiresAt: '2025-01-15',
    expirationDate: '2025-01-15',
    provider: 'Dr. Smith, Portland Vet Clinic',
    veterinarian: 'Dr. Smith',
    lotNumber: 'DHPP2024-001',
    status: 'current',
    notes: '',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 3,
    recordId: 3,
    petId: 1,
    vaccineName: 'Bordetella',
    type: 'Bordetella',
    administeredAt: '2024-06-15',
    administeredDate: '2024-06-15',
    expiresAt: '2024-12-30',
    expirationDate: '2024-12-30',
    provider: 'Dr. Smith, Portland Vet Clinic',
    veterinarian: 'Dr. Smith',
    lotNumber: 'BORD2024-001',
    status: 'expiring',
    notes: 'Due for renewal',
    createdAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 4,
    recordId: 4,
    petId: 2,
    vaccineName: 'Rabies',
    type: 'Rabies',
    administeredAt: '2024-02-20',
    administeredDate: '2024-02-20',
    expiresAt: '2025-02-20',
    expirationDate: '2025-02-20',
    provider: 'Dr. Lee, East Side Animal Hospital',
    veterinarian: 'Dr. Lee',
    lotNumber: 'RAB2024-002',
    status: 'current',
    notes: '',
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 5,
    recordId: 5,
    petId: 2,
    vaccineName: 'DHPP',
    type: 'DHPP',
    administeredAt: '2023-12-01',
    administeredDate: '2023-12-01',
    expiresAt: '2024-12-01',
    expirationDate: '2024-12-01',
    provider: 'Dr. Lee, East Side Animal Hospital',
    veterinarian: 'Dr. Lee',
    lotNumber: 'DHPP2023-012',
    status: 'expired',
    notes: 'EXPIRED - Needs renewal',
    createdAt: '2023-12-01T14:30:00Z',
  },
  {
    id: 6,
    recordId: 6,
    petId: 3,
    vaccineName: 'Rabies',
    type: 'Rabies',
    administeredAt: '2024-11-08',
    administeredDate: '2024-11-08',
    expiresAt: '2025-11-08',
    expirationDate: '2025-11-08',
    provider: 'Dr. Park, Downtown Vet',
    veterinarian: 'Dr. Park',
    lotNumber: 'RAB2024-011',
    status: 'current',
    notes: '',
    createdAt: '2024-11-08T09:00:00Z',
  },
  {
    id: 7,
    recordId: 7,
    petId: 6,
    vaccineName: 'Rabies',
    type: 'Rabies',
    administeredAt: '2024-04-12',
    administeredDate: '2024-04-12',
    expiresAt: '2025-04-12',
    expirationDate: '2025-04-12',
    provider: 'Dr. Smith, Portland Vet Clinic',
    veterinarian: 'Dr. Smith',
    lotNumber: 'RAB2024-004',
    status: 'current',
    notes: '',
    createdAt: '2024-04-12T16:00:00Z',
  },
  {
    id: 8,
    recordId: 8,
    petId: 6,
    vaccineName: 'Bordetella',
    type: 'Bordetella',
    administeredAt: '2024-04-12',
    administeredDate: '2024-04-12',
    expiresAt: '2024-12-28',
    expirationDate: '2024-12-28',
    provider: 'Dr. Smith, Portland Vet Clinic',
    veterinarian: 'Dr. Smith',
    lotNumber: 'BORD2024-004',
    status: 'expiring',
    notes: 'Expires soon',
    createdAt: '2024-04-12T16:00:00Z',
  },
];

const bookings = [
  {
    id: 1,
    recordId: 1,
    petId: 1,
    kennelId: 1,
    startDate: '2024-12-24',
    endDate: '2024-12-28',
    checkInTime: '10:00',
    checkOutTime: '14:00',
    status: 'CONFIRMED',
    serviceType: 'boarding',
    notes: 'Christmas boarding',
    totalAmount: 200.00,
    isPaid: false,
    addons: ['Bath before pickup'],
    createdAt: '2024-12-10T10:00:00Z',
  },
  {
    id: 2,
    recordId: 2,
    petId: 2,
    kennelId: 2,
    startDate: '2024-12-24',
    endDate: '2024-12-26',
    checkInTime: '09:00',
    checkOutTime: '16:00',
    status: 'CONFIRMED',
    serviceType: 'boarding',
    notes: '',
    totalAmount: 100.00,
    isPaid: true,
    addons: [],
    createdAt: '2024-12-15T14:00:00Z',
  },
  {
    id: 3,
    recordId: 3,
    petId: 3,
    kennelId: 3,
    startDate: '2024-12-23',
    endDate: '2024-12-24',
    checkInTime: '08:00',
    checkOutTime: '18:00',
    status: 'CHECKED_IN',
    checkedInAt: '2024-12-23T08:15:00Z',
    serviceType: 'daycare',
    notes: 'Regular daycare customer',
    totalAmount: 45.00,
    isPaid: true,
    addons: [],
    createdAt: '2024-12-20T09:00:00Z',
  },
  {
    id: 4,
    recordId: 4,
    petId: 7,
    kennelId: 4,
    startDate: '2024-12-26',
    endDate: '2025-01-02',
    checkInTime: '11:00',
    checkOutTime: '15:00',
    status: 'CONFIRMED',
    serviceType: 'boarding',
    notes: 'New Year boarding - high energy dog',
    totalAmount: 350.00,
    isPaid: false,
    addons: ['Extra playtime', 'Nail trim'],
    createdAt: '2024-12-18T16:00:00Z',
  },
  {
    id: 5,
    recordId: 5,
    petId: 6,
    kennelId: 5,
    startDate: '2024-12-20',
    endDate: '2024-12-22',
    checkInTime: '10:00',
    checkOutTime: '14:00',
    status: 'CHECKED_OUT',
    checkedInAt: '2024-12-20T10:05:00Z',
    checkedOutAt: '2024-12-22T13:45:00Z',
    serviceType: 'boarding',
    notes: '',
    totalAmount: 100.00,
    isPaid: true,
    addons: [],
    createdAt: '2024-12-15T11:00:00Z',
  },
];

const kennels = [
  { id: 1, name: 'Suite A1', size: 'large', type: 'suite', status: 'available', capacity: 1, dailyRate: 50 },
  { id: 2, name: 'Suite A2', size: 'large', type: 'suite', status: 'available', capacity: 1, dailyRate: 50 },
  { id: 3, name: 'Suite B1', size: 'medium', type: 'suite', status: 'occupied', capacity: 1, dailyRate: 40 },
  { id: 4, name: 'Suite B2', size: 'medium', type: 'suite', status: 'available', capacity: 1, dailyRate: 40 },
  { id: 5, name: 'Run C1', size: 'large', type: 'run', status: 'available', capacity: 2, dailyRate: 35 },
  { id: 6, name: 'Run C2', size: 'large', type: 'run', status: 'available', capacity: 2, dailyRate: 35 },
  { id: 7, name: 'Kennel D1', size: 'small', type: 'kennel', status: 'available', capacity: 1, dailyRate: 30 },
  { id: 8, name: 'Kennel D2', size: 'small', type: 'kennel', status: 'available', capacity: 1, dailyRate: 30 },
  { id: 9, name: 'Cat Suite 1', size: 'small', type: 'cat', status: 'available', capacity: 1, dailyRate: 25 },
  { id: 10, name: 'Cat Suite 2', size: 'small', type: 'cat', status: 'available', capacity: 1, dailyRate: 25 },
];

const tasks = [
  {
    id: 1,
    title: 'Morning Feeding - All Dogs',
    type: 'FEEDING',
    status: 'PENDING',
    scheduledFor: '2024-12-24T07:00:00Z',
    assignedTo: 'staff-1',
    priority: 'HIGH',
    notes: '',
    createdAt: '2024-12-23T18:00:00Z',
  },
  {
    id: 2,
    title: 'Medication - Luna',
    type: 'MEDICATION',
    status: 'PENDING',
    scheduledFor: '2024-12-24T08:00:00Z',
    petId: 2,
    petName: 'Luna',
    assignedTo: 'staff-1',
    priority: 'HIGH',
    notes: 'Joint supplement with breakfast',
    createdAt: '2024-12-23T18:00:00Z',
  },
  {
    id: 3,
    title: 'Playtime - Max',
    type: 'EXERCISE',
    status: 'PENDING',
    scheduledFor: '2024-12-24T10:00:00Z',
    petId: 3,
    petName: 'Max',
    assignedTo: 'staff-2',
    priority: 'MEDIUM',
    notes: '30 minutes outdoor play',
    createdAt: '2024-12-23T18:00:00Z',
  },
  {
    id: 4,
    title: 'Clean Suite A1',
    type: 'CLEANING',
    status: 'COMPLETED',
    scheduledFor: '2024-12-23T14:00:00Z',
    completedAt: '2024-12-23T14:30:00Z',
    assignedTo: 'staff-2',
    priority: 'MEDIUM',
    notes: '',
    createdAt: '2024-12-23T08:00:00Z',
  },
  {
    id: 5,
    title: 'Evening Feeding - All Dogs',
    type: 'FEEDING',
    status: 'PENDING',
    scheduledFor: '2024-12-24T17:00:00Z',
    assignedTo: 'staff-1',
    priority: 'HIGH',
    notes: '',
    createdAt: '2024-12-23T18:00:00Z',
  },
];

const staff = [
  {
    id: 'staff-1',
    firstName: 'Alex',
    lastName: 'Martinez',
    email: 'alex@happypaws.com',
    phone: '(555) 111-2222',
    role: 'MANAGER',
    status: 'ACTIVE',
    hireDate: '2022-01-15',
    createdAt: '2022-01-15T09:00:00Z',
  },
  {
    id: 'staff-2',
    firstName: 'Jordan',
    lastName: 'Lee',
    email: 'jordan@happypaws.com',
    phone: '(555) 222-3333',
    role: 'ATTENDANT',
    status: 'ACTIVE',
    hireDate: '2023-03-20',
    createdAt: '2023-03-20T09:00:00Z',
  },
  {
    id: 'staff-3',
    firstName: 'Casey',
    lastName: 'Brown',
    email: 'casey@happypaws.com',
    phone: '(555) 333-4444',
    role: 'ATTENDANT',
    status: 'ACTIVE',
    hireDate: '2023-08-01',
    createdAt: '2023-08-01T09:00:00Z',
  },
];

const services = [
  { id: 1, name: 'Boarding', description: 'Overnight stay', basePrice: 50, unit: 'night', isActive: true },
  { id: 2, name: 'Daycare', description: 'Full day care', basePrice: 35, unit: 'day', isActive: true },
  { id: 3, name: 'Grooming', description: 'Bath and groom', basePrice: 60, unit: 'session', isActive: true },
  { id: 4, name: 'Training', description: 'Basic obedience', basePrice: 75, unit: 'hour', isActive: true },
];

const addonServices = [
  { id: 1, name: 'Extra Playtime', description: '30 min extra play', price: 15, isActive: true },
  { id: 2, name: 'Bath', description: 'Full bath before pickup', price: 25, isActive: true },
  { id: 3, name: 'Nail Trim', description: 'Nail trimming service', price: 15, isActive: true },
  { id: 4, name: 'Medication Administration', description: 'Per dose', price: 5, isActive: true },
];

const notifications = [
  {
    id: 1,
    title: 'New Booking',
    message: 'Sarah Johnson booked Buddy for Dec 24-28',
    type: 'BOOKING',
    read: false,
    createdAt: '2024-12-10T10:00:00Z',
  },
  {
    id: 2,
    title: 'Vaccination Expiring',
    message: "Buddy's Bordetella expires in 6 days",
    type: 'VACCINATION',
    read: false,
    createdAt: '2024-12-24T08:00:00Z',
  },
  {
    id: 3,
    title: 'Check-in Complete',
    message: 'Max checked in for daycare',
    type: 'CHECKIN',
    read: true,
    createdAt: '2024-12-23T08:15:00Z',
  },
];

const settings = {
  businessName: 'Happy Paws Pet Resort',
  address: '100 Pet Paradise Lane',
  city: 'Portland',
  state: 'OR',
  zipCode: '97201',
  phone: '(555) 123-4567',
  email: 'info@happypaws.com',
  timezone: 'America/Los_Angeles',
  currency: 'USD',
  defaultCheckInTime: '10:00',
  defaultCheckOutTime: '14:00',
};

// ============================================================================
// SEEDER FUNCTION
// ============================================================================

export const seedDemoData = () => {
  const demoData = {
    owners,
    pets,
    vaccinations,
    bookings,
    kennels,
    tasks,
    staff,
    services,
    addonServices,
    notifications,
    settings,
    _seededAt: new Date().toISOString(),
    _version: '1.0.0',
  };

  sessionStorage.setItem(DEMO_STORAGE_KEY, JSON.stringify(demoData));
  console.log('[DEMO] Data seeded successfully');
  return demoData;
};

export const resetDemoData = () => {
  sessionStorage.removeItem(DEMO_STORAGE_KEY);
  seedDemoData();
  console.log('[DEMO] Data reset successfully');
};

export const isDemoDataSeeded = () => {
  return sessionStorage.getItem(DEMO_STORAGE_KEY) !== null;
};
