export const queryKeys = {
  tenant: (tenantKey) => ['tenant', tenantKey],
  // Base dashboard function for building query keys
  dashboard: (tenantKey) => [tenantKey, 'dashboard'],
  // Nested dashboard keys for backwards compatibility
  dashboardKeys: {
    stats: (tenantKey) => [tenantKey, 'dashboard', 'stats'],
    occupancy: (tenantKey) => [tenantKey, 'dashboard', 'occupancy'],
    vaccinations: (tenantKey) => [tenantKey, 'dashboard', 'vaccinations'],
    shiftHandoff: (tenantKey) => [tenantKey, 'dashboard', 'shift-handoff'],
    emergencyAccess: (tenantKey) => [tenantKey, 'dashboard', 'emergency-access'],
    wellnessMonitoring: (tenantKey) => [tenantKey, 'dashboard', 'wellness-monitoring'],
    parentCommunication: (tenantKey) => [tenantKey, 'dashboard', 'parent-communication'],
    facilityHeatmap: (tenantKey) => [tenantKey, 'dashboard', 'facility-heatmap'],
    revenueOptimizer: (tenantKey) => [tenantKey, 'dashboard', 'revenue-optimizer'],
    socialCompatibility: (tenantKey) => [tenantKey, 'dashboard', 'social-compatibility'],
    staffingIntelligence: (tenantKey) => [tenantKey, 'dashboard', 'staffing-intelligence'],
    customerCLV: (tenantKey) => [tenantKey, 'dashboard', 'customer-clv'],
    incidentAnalytics: (tenantKey) => [tenantKey, 'dashboard', 'incident-analytics'],
  },
  bookings: (tenantKey, filters = {}) => [tenantKey, 'bookings', filters],
  pets: (tenantId) => ['pets', { tenantId }],
  userProfile: (userId, tenantId) => ['userProfile', { userId, tenantId }],
  kennels: (tenantKey, params = {}) => [tenantKey, 'kennels', params],
  owners: (tenantKey, params = {}) => [tenantKey, 'owners', params],
  payments: (tenantKey, params = {}) => [tenantKey, 'payments', params],
  paymentsSummary: (tenantKey) => [tenantKey, 'payments', 'summary'],
  incidents: (tenantKey, params = {}) => [tenantKey, 'incidents', params],
  calendar: (tenantKey, params = {}) => [tenantKey, 'calendar', params],
  occupancy: (tenantKey, params = {}) => [tenantKey, 'occupancy', params],
  suggestKennel: (tenantKey, params = {}) => [tenantKey, 'suggest-kennel', params],
  reports: {
    dashboard: (tenantKey, params = {}) => [tenantKey, 'reports', 'dashboard', params],
  },
  staff: (tenantKey) => [tenantKey, 'staff'],
  members: (tenantKey) => [tenantKey, 'members'],
  onboarding: (tenantKey) => [tenantKey, 'onboarding'],
  properties: (tenantKey, params = {}) => [tenantKey, 'properties', params],
  services: (tenantKey) => [tenantKey, 'services'],
  runs: (tenantKey, params = {}) => [tenantKey, 'runs', params],
  tasks: (tenantKey, params = {}) => [tenantKey, 'tasks', params],
  facilitySettings: (tenantKey) => [tenantKey, 'facility-settings'],
  associations: (tenantKey, params = {}) => [tenantKey, 'associations', params],
  notifications: {
    unreadCount: (tenantKey) => [tenantKey, 'notifications', 'unread-count'],
    list: (tenantKey, params = {}) => [tenantKey, 'notifications', 'list', params],
  },
};
